export default {
	trackId: { type: Number, unique: true },
	title: { type: String },
	artworkUrl: { type: String },
	soundcloudCreatedAt: { type: Date },
	duration: { type: Number },
	genre: { type: String },
	kind: { type: String },
	license: { type: String },
	likesCount: { type: Number },
	playbackCount: { type: Number },
	public: { type: Boolean },
	tagList: { type: String },
	userId: { type: Number },
	username: { type: String },
	userPermalink: { type: String },
	trackFormat: { type: String },
	permalink: { type: String },
	monetizationModel: { type: String },
	policy: { type: String },
	streamable: { type: Boolean },
	sharing: { type: String },
	state: { type: String },
	embeddableBy: { type: String },
	createdAt: { type: Date, default: Date.now, required: true },
	documentVersion: { type: Number, default: 1, required: true }
};
