name: Musare Lint

on: [ push, pull_request, workflow_dispatch ]

env:
    COMPOSE_PROJECT_NAME: musare
    APP_ENV: development
    MONGO_ROOT_PASSWORD: PASSWORD_HERE
    MONGO_USER_USERNAME: musare
    MONGO_USER_PASSWORD: OTHER_PASSWORD_HERE
    MONGO_VERSION: 5.0
    REDIS_PASSWORD: PASSWORD

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Musare
              run: |
                  cp .env.example .env
                  sed -i 's/APP_ENV=production/APP_ENV=development/g' .env
                  ./musare.sh build
            - name: Start Musare
              run: ./musare.sh start
            - name: Backend Lint
              run: ./musare.sh lint backend
            - name: Frontend Lint
              run: ./musare.sh lint frontend
            - name: Docs Lint
              run: ./musare.sh lint docs
